#!/bin/sh
BASEDIR=`dirname $0`/../Resources
exec java \
	-d32 \
	-XstartOnFirstThread \
	-classpath $BASEDIR/swt/swt.jar:$BASEDIR/md5/fast-md5.jar:$BASEDIR \
	-Djava.library.path=$BASEDIR/swt \
	nu.dll.duper.GUI
